[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "cd backend && java -Xmx200m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -Xss512k -Dserver.port=$PORT -jar target/*.jar"
