spring:
  main:
    lazy-initialization: false
  application:
    name: gym-routine-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:gymdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 2



server:
  port: ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

youtube:
  api:
    key: ${YOUTUBE_API_KEY:}

ai:
  groq:
    api-key: ${AI_GROQ_API_KEY:}
  gemini:
    api-key: ${AI_GEMINI_API_KEY:}
  mistral:
    api-key: ${AI_MISTRAL_API_KEY:}
  huggingface:
    api-key: ${AI_HUGGINGFACE_API_KEY:}
